# ABOUTME: Docker Compose configuration for integration test infrastructure
# ABOUTME: Provides PostgreSQL service for real integration testing

version: '3.8'

services:
  # PostgreSQL Database for Integration Tests
  test-postgres:
    image: postgres:16-alpine
    container_name: animanga-test-postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: animanga_test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d animanga_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

volumes:
  test-postgres-data:
    driver: local

networks:
  test-network:
    driver: bridge
    name: animanga-test-network