version: '3.8'

services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        environment:
            - FLASK_ENV=development
            - PYTHONUNBUFFERED=1
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "python", "/app/verify_flask_setup.py"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    frontend:
        build:
            context: ./frontend
            target: development  # Use development stage by default
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - REACT_APP_API_BASE_URL=http://localhost:5000
            - CHOKIDAR_USEPOLLING=true  # For hot reload in Docker
        depends_on:
            - backend
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    app-network:
        driver: bridge