version: '3.8'

services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        environment:
            - FLASK_ENV=development
            - PYTHONUNBUFFERED=1

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - REACT_APP_API_BASE_URL=http://localhost:5000
        depends_on:
            - backend